window.HDS_NAV = [
  {
    label: "GUIDE",
    items: [
      { id: "start", label: "Start", next: "philosophy", nextLabel: "Next — Philosophy" },
      { id: "philosophy", label: "Philosophy", next: "principles", nextLabel: "Next — Principles" },
      { id: "principles", label: "Principles", next: "voice", nextLabel: "Next — Voice & tone" },
      { id: "voice", label: "Voice", next: "colour", nextLabel: "Next — Colour" },
    ],
  },
  {
    label: "FOUNDATIONS",
    items: [
      { id: "colour", label: "Colour", next: "typography", nextLabel: "Next — Typography" },
      { id: "typography", label: "Typography", next: "spacing", nextLabel: "Next — Spacing" },
      { id: "spacing", label: "Spacing", next: "radius", nextLabel: "Next — Radius" },
      { id: "radius", label: "Radius", next: "elevation", nextLabel: "Next — Elevation" },
      { id: "elevation", label: "Elevation", next: "grid", nextLabel: "Next — Grid" },
      { id: "grid", label: "Grid", next: "logo", nextLabel: "Next — Logo" },
      { id: "logo", label: "Logo", next: "iconography", nextLabel: "Next — Iconography" },
      { id: "iconography", label: "Iconography", next: "button", nextLabel: "Next — Button" },
    ],
  },
  {
    label: "COMPONENTS",
    items: [
      { id: "button", label: "Button", next: "fields", nextLabel: "Next — Fields" },
      { id: "fields", label: "Fields", next: "selection", nextLabel: "Next — Selection" },
      { id: "selection", label: "Selection", next: "chips", nextLabel: "Next — Chips" },
      { id: "chips", label: "Chips", next: "badge", nextLabel: "Next — Badge" },
      { id: "badge", label: "Badge", next: "badge-grid", nextLabel: "Next — Badge grid" },
      { id: "badge-grid", label: "Badge grid", next: "avatar", nextLabel: "Next — Avatar" },
      { id: "avatar", label: "Avatar", next: "tile", nextLabel: "Next — Tile" },
      { id: "tile", label: "Tile", next: "divider", nextLabel: "Next — Divider" },
      { id: "divider", label: "Divider", next: "filter", nextLabel: "Next — Filter" },
      { id: "filter", label: "Filter", next: "dropdown", nextLabel: "Next — Dropdown" },
      { id: "dropdown", label: "Dropdown", next: "stepper", nextLabel: "Next — Stepper" },
      { id: "stepper", label: "Stepper", next: "table", nextLabel: "Next — Table" },
      { id: "table", label: "Table", next: "toast", nextLabel: "Next — Toast" },
      { id: "toast", label: "Toast", next: "modal", nextLabel: "Next — Modal" },
      { id: "modal", label: "Modal", next: "info-panel", nextLabel: "Next — Info panel" },
      { id: "info-panel", label: "Info panel", next: "action-bar", nextLabel: "Next — Action bar" },
      { id: "action-bar", label: "Action bar", next: "chat", nextLabel: "Next — Chat" },
      { id: "chat", label: "Chat", next: "interaction-bars", nextLabel: "Next — Interaction bars" },
    ],
  },
  {
    label: "INTERACTION BARS",
    items: [{ id: "interaction-bars", label: "All bars", next: "header-nav", nextLabel: "Next — Header nav" }],
  },
  {
    label: "NAVIGATION",
    items: [
      { id: "header-nav", label: "Header nav", next: "bottom-bar", nextLabel: "Next — Bottom bar" },
      { id: "bottom-bar", label: "Bottom bar", deprecated: true, next: "footer", nextLabel: "Next — Footer" },
      { id: "footer", label: "Footer" },
    ],
  },
];

window.HDS_FIGMA_NODES = {
  colour: "94:612",
  typography: "95:849",
  spacing: "96:884",
  radius: "96:1116",
  elevation: "97:954",
  grid: "98:989",
  logo: "106:1301",
  iconography: "107:1156",
  button: "51:3",
  fields: "86:446",
  selection: "103:740",
  chips: "92:551",
  badge: "103:1060",
  "badge-grid": "111:5750",
  avatar: "104:800",
  tile: "104:1045",
  divider: "104:1325",
  filter: "108:3051",
  dropdown: "108:3592",
  stepper: "108:4085",
  table: "109:3671",
  toast: "109:5159",
  modal: "109:5676",
  "info-panel": "111:4985",
  "action-bar": "111:6178",
  chat: "112:5808",
  "interaction-bars": "113:6994",
  "header-nav": "114:10847",
  "bottom-bar": "114:12242",
  footer: "175:8846",
  start: "45:3",
  philosophy: "46:3",
  principles: "26:3",
  voice: "50:3",
};
